# Usar apenas Nginx para servir os arquivos já buildados
FROM nginx:stable-alpine

# Copiar arquivos de build já prontos
COPY build /usr/share/nginx/html

# Copiar configuração do nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Expor porta 80
EXPOSE 80

# Comando para iniciar nginx
CMD ["nginx", "-g", "daemon off;"]
